name: 'Swap Space'
description: 'Add swap space.'
branding:
  icon: 'crop'
  color: 'blue'
inputs:
  swap-size-gb:
    description: 'Swap space in GB.'
    required: false
    default: '10'
runs:
  using: "composite"
  steps:
    - name: Swap space report before modification
      shell: bash
      run: |
        echo "Memory swap:"
        free -h
        echo
        swapon --show
        echo
    - name: Set Swap
      shell: bash
      run: |
          export SWAP_FILE=$(swapon --show=NAME | tail -n 1)
          sudo swapoff $SWAP_FILE
          sudo rm $SWAP_FILE
          sudo fallocate -l ${{ inputs.swap-size-gb }}G $SWAP_FILE
          sudo chmod 600 $SWAP_FILE
          sudo mkswap $SWAP_FILE
          sudo swapon $SWAP_FILE
    - name: Swap space report after modification
      shell: bash
      run: |
        echo "Memory and swap:"
        free -h
        echo
        swapon --show
        echo
